# Generated by Django 4.2.1 on 2023-05-14 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="trialrecord",
            name="max_score",
        ),
        migrations.RemoveField(
            model_name="trialrecord",
            name="min_score",
        ),
        migrations.AddField(
            model_name="examination",
            name="max_score",
            field=models.IntegerField(default=10, null=True),
        ),
        migrations.AddField(
            model_name="examination",
            name="min_score",
            field=models.IntegerField(default=0, null=True),
        ),
    ]
