# Generated by Django 4.2.1 on 2023-06-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("course", "0002_remove_trialrecord_max_score_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="url",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
